### ISSUE TITLE
radxa camera 8M 219 doesn't work

### ISSUE THREAD

**Issue by digitalshamansky** [radxa-build/radxa-zero3#10]
Hello, tried different distros and kernels for Radxa3w, and can't get camera working. Camera is detected by media-ctl -p

media-ctl -p
Media controller API version 6.1.43

Media device information
------------------------
driver          rkisp-vir0
model           rkisp0
serial          
bus info        platform:rkisp-vir0
hw revision     0x0
driver version  6.1.43

Device topology
- entity 1: rkisp-isp-subdev (4 pads, 8 links)
            type V4L2 subdev subtype Unknown flags 0
            device node name /dev/v4l-subdev0
        pad0: Sink
                [fmt:SRGGB8_1X8/800x600 field:none
                 crop.bounds:(0,0)/800x600
                 crop:(0,0)/800x600]
                <- "rkisp-csi-subdev":1 [ENABLED]
                <- "rkisp_rawrd0_m":0 []
                <- "rkisp_rawrd2_s":0 []
        pad1: Sink
                <- "rkisp-input-params":0 [ENABLED]
        pad2: Source
                [fmt:YUYV8_2X8/800x600 field:none colorspace:smpte170m quantization:full-range
                 crop.bounds:(0,0)/800x600
                 crop:(0,0)/800x600]
                -> "rkisp_mainpath":0 [ENABLED]
                -> "rkisp_selfpath":0 [ENABLED]
                -> "rkisp_iqtool":0 [ENABLED]
        pad3: Source
                -> "rkisp-statistics":0 [ENABLED]

- entity 6: rkisp-csi-subdev (6 pads, 5 links)
            type V4L2 subdev subtype Unknown flags 0
            device node name /dev/v4l-subdev1
        pad0: Sink
                <- "rockchip-csi2-dphy0":1 [ENABLED]
        pad1: Source
                -> "rkisp-isp-subdev":0 [ENABLED]
        pad2: Source
                -> "rkisp_rawwr0":0 [ENABLED]
        pad3: Source
        pad4: Source
                -> "rkisp_rawwr2":0 [ENABLED]
        pad5: Source
                -> "rkisp_rawwr3":0 [ENABLED]

- entity 13: rkisp_mainpath (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video0
        pad0: Sink
                <- "rkisp-isp-subdev":2 [ENABLED]

- entity 19: rkisp_selfpath (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video1
        pad0: Sink
                <- "rkisp-isp-subdev":2 [ENABLED]

- entity 25: rkisp_rawwr0 (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video2
        pad0: Sink
                <- "rkisp-csi-subdev":2 [ENABLED]

- entity 31: rkisp_rawwr2 (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video3
        pad0: Sink
                <- "rkisp-csi-subdev":4 [ENABLED]

- entity 37: rkisp_rawwr3 (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video4
        pad0: Sink
                <- "rkisp-csi-subdev":5 [ENABLED]

- entity 43: rkisp_iqtool (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video5
        pad0: Sink
                <- "rkisp-isp-subdev":2 [ENABLED]

- entity 49: rkisp_rawrd0_m (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video6
        pad0: Source
                -> "rkisp-isp-subdev":0 []

- entity 55: rkisp_rawrd2_s (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video7
        pad0: Source
                -> "rkisp-isp-subdev":0 []

- entity 61: rkisp-statistics (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video8
        pad0: Sink
                <- "rkisp-isp-subdev":3 [ENABLED]

- entity 67: rkisp-input-params (1 pad, 1 link)
             type Node subtype V4L flags 0
             device node name /dev/video9
        pad0: Source
                -> "rkisp-isp-subdev":1 [ENABLED]

- entity 73: rockchip-csi2-dphy0 (2 pads, 1 link)
             type V4L2 subdev subtype Unknown flags 0
             device node name /dev/v4l-subdev2
        pad0: Sink
        pad1: Source
                -> "rkisp-csi-subdev":0 [ENABLED]

but when I try to use Gstreamer - I see and error : 

gst-launch-1.0 v4l2src device=/dev/video0 io-mode=4 ! videoconvert ! video/x-raw,format=NV12,width=1920,height=1080 ! jpegenc ! multifilesink location=/home/radxa/test.jpg
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
[  231.642825] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
Pipeline is PREROLLED ...
[  231.643271] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
Setting pipeline to PLAYING ...
[  231.643384] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
New clock: GstSystemClock
[  231.643446] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
[  231.643514] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
Additional debug info:
[  231.643570] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
[  231.643618] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
streaming stopped, reason not-negotiated (-4)
[  231.643665] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
Execution ended after 0:00:00.002814292
[  231.643714] rkisp-vir0: rkisp_enum_frameintervals Not active sensor
Setting pipeline to NULL ...
Freeing pipeline ...

Is there any special things needs to be done ? Camera is correctly connected accroding to the official documentation.

**Comment by RadxaYuntian** [comment]
Did you figure it out? What was the cause?
