### ISSUE TITLE
Radxa Camera 8M don't work

### ISSUE THREAD

**Issue by nerbivol** [radxa-build/radxa-zero3#15]
### System Configuration

I use Radxa Camera 8M and choose Raspberry Pi Camera V2 (because Radxa Camera 8M does not exist in `rsetup`).
![image](https://github.com/radxa-docs/docs/assets/68056715/d22a36eb-3490-4a17-a96f-09e85c67f07b)
In the file `/boot/extlinux/extlinux.conf`, the code is as follows:
```bash
# /boot/extlinux/extlinux.conf

##
## IMPORTANT WARNING
##
## The configuration of this file is generated automatically.
## Do not edit this file manually, use: u-boot-update
##

default l0
menu title U-Boot menu
prompt 1
timeout 10

label l0
  menu label Debian GNU/Linux 11 (bullseye) 5.10.160-26-rk356x
  linux /boot/vmlinuz-5.10.160-26-rk356x
  initrd /boot/initrd.img-5.10.160-26-rk356x
  fdt /usr/lib/linux-image-5.10.160-26-rk356x/
  fdtoverlay /boot/dtbo/radxa-zero3-rpi-camera-v2.dtbo
  append root=UUID=e4dcf7b3-d6e7-4a53-8267-d85088ac4ff3 console=ttyFIQ0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

label l0r
  menu label Debian GNU/Linux 11 (bullseye) 5.10.160-26-rk356x (rescue target)
  linux /boot/vmlinuz-5.10.160-26-rk356x
  initrd /boot/initrd.img-5.10.160-26-rk356x
  fdt /usr/lib/linux-image-5.10.160-26-rk356x/
  fdtoverlay /boot/dtbo/radxa-zero3-rpi-camera-v2.dtbo
  append root=UUID=e4dcf7b3-d6e7-4a53-8267-d85088ac4ff3 console=ttyFIQ0,1500000n8 splash loglevel=4 rw earlycon consoleblank=0 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 single
```

When I run the command `sudo cheese`, I get the following error:
```bash
(cheese:1621): cheese-WARNING **: 09:19:15.883: Failed to allocate required memory... ../sys/v4l2/gstv4l2src.c(700): gst_v4l2src_decide_allocation (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin28/GstV4l2Src:v4l2src1:
Buffer pool activation failed
```
When I run the following GStreamer pipeline:
```bash
radxa@radxa-zero3:~$ gst-launch-1.0 v4l2src device=/dev/video0 io-mode=4 ! videoconvert ! video/x-raw,format=NV12,width=1920,height=1080 ! jpegenc ! multifilesink location=/home/radxa/test.jpg
```

I get this error:
```bash
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.003069317
Setting pipeline to NULL ...
Freeing pipeline ...
```

### USB Devices
```bash
radxa@radxa-zero3:~$ lsusb
Bus 006 Device 002: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub             
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 004: ID 1a2c:2c27 China Resource Semico Co., Ltd USB Keyboard
Bus 005 Device 003: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 005 Device 002: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

### Video Devices
```bash
radxa@radxa-zero3:~$ v4l2-ctl --list-devices
rkisp-statistics (platform: rkisp):
	/dev/video7
	/dev/video8

rkisp_mainpath (platform:rkisp-vir0):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/video4
	/dev/video5
	/dev/video6
	/dev/media0
```

**Comment by RadxaYuntian** [comment]
What is the result when you run `rsetup` - Hardware - Video capture devices? It should save a picture under /root/ folder.

**Comment by nerbivol** [comment]
![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/f08f1e50-44b5-4994-a95f-4e3fb3a851c0)

and output in terminal

![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/b932818f-f8af-4e38-afb5-4e19074ef9b0)

**Comment by nerbivol** [comment]
Hardware connections are as follows:
![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/97d3be29-6c38-4f97-9e26-be340ebb0a78)

**Comment by RadxaYuntian** [comment]
I forgot there was an issue in currently released `rsetup` regarding camera test. It was fixed in [0.4.6](https://github.com/radxa-pkg/rsetup/releases/tag/0.4.6) but it is not released yet.

We will take a look at this.

**Comment by nerbivol** [comment]
Code for update to 0.4.6 version:
```
sudo apt-get update
sudo apt-get build-dep --no-install-recommends .
sudo apt-get install git-buildpackage
```
```
wget https://github.com/radxa-pkg/rsetup/releases/download/0.4.6/rsetup_0.4.6_all.deb
sudo dpkg -i rsetup_0.4.6_all.deb 
```

And results from `rsetup` video capture
![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/cdeb44d4-0a97-47d4-8d8e-1c76c0541b03)

Otput from terminal:

```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Failed to allocate required memory.
Additional debug info:
../sys/v4l2/gstv4l2src.c(700): gst_v4l2src_decide_allocation (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Buffer pool activation failed
Execution ended after 0:00:00.020098472
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Freeing pipeline ...

```

**Comment by Sviatoslav007** [comment]
I have a similar problem, the camera from Radxa does not want to connect to the Radxa zero W3 board, which is a very strange problem, given that the software is from the same manufacturer @RadxaYuntian

**Comment by Radxa-Alvin** [comment]
Please run the following command to see it，check whether the camera is mounted successfully
`sudo dmesg | grep imx`

**Comment by nerbivol** [comment]
```
radxa@radxa-zero3:~$ sudo dmesg | grep imx

[sudo] password for radxa: 
[   19.989369] imx219 2-0010: driver version: 00.01.01
[   20.092275] imx219 2-0010: Reading register 100 from 10 failed
[   20.195585] imx219 2-0010: Reading register 100 from 10 failed
[   20.507604] imx219 2-0010: Error -5 setting default controls
[   20.507850] imx219: probe of 2-0010 failed with error -5
```

**Comment by Radxa-Alvin** [comment]
It looks like the camera didn't load properly.Need to check whether the cable and camera are normal.

**Comment by nerbivol** [comment]
It seems the camera isn't working. The cable is connected as shown in the [documentation](https://docs.radxa.com/en/zero/zero3/accessories/camera) (we've also tried different connections and cables), but we haven't had any success. 
Do you have functional Radxa camera and Radxa ZERO 3w board units?

**Comment by nerbivol** [comment]
> Please run the following command to see it，check whether the camera is mounted successfully `sudo dmesg | grep imx`

```
radxa@radxa-zero3:~$ sudo dmesg | grep imx
[sudo] password for radxa: 
[   19.844757] imx219 2-0010: driver version: 00.01.01
[   19.869602] imx219 2-0010: Model ID 0x0219, Lot ID 0x5b2402, Chip ID 0x06d1
[   19.880573] rockchip-csi2-dphy csi2-dphy0: dphy0 matches m00_b_imx219 2-0010:bus type 5

```
@Radxa-Alvin does this mean I have a properly connected camera?

**Comment by nerbivol** [comment]
### Update for Current State:

I am encountering multiple errors when executing certain commands on my Radxa Zero 3 device.

#### Command 1:
```
radxa@radxa-zero3:~$ sudo rsetup
[sudo] password for radxa: 
error: XDG_RUNTIME_DIR not set in the environment.
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Cannot identify device '/dev/Capture a picture'.
Additional debug info:
../sys/v4l2/v4l2_calls.c(608): gst_v4l2_open (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
system error: No such file or directory
ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...
```

#### Command 2:
```
radxa@radxa-zero3:~$ gst-launch-1.0 v4l2src device=/dev/video0 io-mode=4 ! videoconvert ! video/x-raw,format=NV12,width=1920,height=1080 ! jpegenc ! multifilesink location=/home/radxa/test.jpg
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:19.053323709
Setting pipeline to NULL ...
Freeing pipeline ...
```
- I do not encounter errors here, but when I press `Ctrl+C` to take a picture, the photo is not saved in `/home/radxa/test.jpg`.

#### Command 3:
```
radxa@radxa-zero3:~$ sudo cheese
[sudo] password for radxa:
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
error: XDG_RUNTIME_DIR not set in the environment.

(cheese:2509): dconf-WARNING **: 10:09:57.859: failed to commit changes to dconf: 
Failed to execute child process “dbus-launch” (No such file or directory)
...
```

Please let me know if you need more details or further clarification.

**Comment by nerbivol** [comment]
Can I get any advice or suggestions to help resolve these issues?

**Comment by RadxaYuntian** [comment]
Can you please take a picture of the back of your ZERO 3? Focus on the CSI connector.

**Comment by nerbivol** [comment]
![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/9293659f-a9cd-4822-aac9-9fdfb308a03d)

**Comment by RadxaYuntian** [comment]
We recently found out that some ZERO 3 uses the wrong CSI connector, which is the one you are having. Those systems will need a different CSI cable, which we plan to provide to the affected customer free of charge. For now please disconnect the camera from ZERO 3 to avoid potential malfunction due to incompatible cable.

Do you happen to still have the card box around? We'd like to check the serial number to determine the affected batch.

**Comment by nerbivol** [comment]
![image](https://github.com/radxa-build/radxa-zero3/assets/68056715/59e96e2a-638a-4961-87e5-da57ad9c1061)

**Comment by RadxaYuntian** [comment]
Thanks, and I assume both are having camera issue right?

**Comment by nerbivol** [comment]
Yes

**Comment by RadxaYuntian** [comment]
Thanks. I'll contact you again once the cable is ready.

**Comment by nerbivol** [comment]
Can you provide an approximate waiting time for cable production?

**Comment by nerbivol** [comment]
Understood. Thank you for your quick response. I look forward to further updates from you

**Comment by RadxaYuntian** [comment]
Hi nerbivol. The special CSI cable is now ready. Please send your shipping info to support@radxa.com as well as the quantity of affected ZERO 3. We will arrange the shipping to you shortly.

**Comment by nerbivol** [comment]
We've received the special CSI cable, and I'm happy to report that the camera is working perfectly.

**Comment by RadxaYuntian** [comment]
Future users with camera issue should contact support@radxa.com directly. This issue is now locked.
