### ISSUE TITLE
Unable to use UART get nothig but garbled text in console using working USB to UART interface?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [radxa-build/radxa-zero3#18]
I have used USB to UART for console access on various SBCs, Pi devices, and others.  I am using a working USB to UART 3.3v interface and a brand new Zero 3E.  I have tested the USB to UART cable and interface device with Pi Zero 2W, it works as expected.  But with the Zero 3E no success.

I have set the baud rate to 921600, 8, 1, 0, 0.  I am using PuTTY as per the example in the documentation, but all I get is what appears to garbled text.  The 3 ZERO E image if direct download from web site, it is the bullseyes CLI image from here on github.  Flashed image with balenEcher again per the instructions.

![image](https://github.com/user-attachments/assets/ead73fb5-ec43-4289-8aa1-7ee230bceab1)
![image](https://github.com/user-attachments/assets/c0c7385d-b59d-4e1b-b1f0-199bbcdf4133)

Any help appreciated.

**Comment by Jibun-no-Kage** [comment]
Connected to HDMI, and at boot... reports rootfs clean.... then NOTHING.  The SBC seems to halt, the LED on board turns off.

**Comment by RadxaYuntian** [comment]
Our documentation clearly states that [the baud is 1500000](https://docs.radxa.com/en/zero/zero3/low-level-dev/serial), not 921600.

**Comment by Jibun-no-Kage** [comment]
It does now... the web page I found via the Radxa site showed 921600... I should have screen printed it.  I am not crazy the web page showed at the time I saw a baud rate of 921600... did the web site get updated in the as couple of days?  I guess so.

**Comment by Jibun-no-Kage** [comment]
The base CLI image for bullseye crashes or halts.  But the xfce bullseye image loads successfully....
radxa-zero3_debian_bullseye_xfce_b3.img.xz

**Comment by Jibun-no-Kage** [comment]
Guess I cannot use any of the official images?  Only one that does not fail to load or crash thus far is...
[ubuntu-24.04-preinstalled-server-arm64-radxa-zero3.img.xz](https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.3.0/ubuntu-24.04-preinstalled-server-arm64-radxa-zero3.img.xz)

**Comment by RadxaYuntian** [comment]
> It does now... the web page I found via the Radxa site showed 921600... I should have screen printed it. I am not crazy the web page showed at the time I saw a baud rate of 921600... did the web site get updated in the as couple of days? I guess so.

That was part of the documentation since [April 28](https://github.com/radxa-docs/docs/blob/50e7b0453521b58c02fba398ed0b935a67fdf81a/i18n/en/docusaurus-plugin-content-docs/current/common/general/_serial.mdx?plain=1#L26). You most likely was viewing pages for Mediatek devices. which indeed uses 921600 baud.

> Guess I cannot use any of the official images? Only one that does not fail to load or crash thus far is...

Only the desktop image is supported now. CLI image will be removed in the future.

**Comment by Jibun-no-Kage** [comment]
Ah... still wish I had screen printed it so I had the reference, to confirm.  But beyond that, thanks for the confirmation about the CLI image.  Having created 100s of microSD cards over the years... it was a puzzle.
