### ISSUE TITLE
UART2_M0 Configuration Causes Radxa Zero 3 to Fail Boot

### ISSUE THREAD

**Issue by nerbivol** [radxa-build/radxa-zero3#19]
I need to configure `UART2_M0` as a normal serial port. I followed the instructions provided in the [Radxa documentation](https://docs.radxa.com/en/zero/zero3/os-config/rsetup#overlays). In `rsetup`, I set the `Enable UART2-M0` option to `*`. When Radxa is already running, everything works fine. However, after a reboot, the Radxa device fails to boot.

It seems like I need to modify the Linux boot parameters. My current `/etc/kernel/cmdline` looks like this:
```
console=ttyFIQ0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
```

**Question**:
- What exactly do I need to remove from this file? Should I delete everything except `console=ttyFIQ0,1500000n8`, or is there something else I need to consider?

**Comment by RadxaYuntian** [comment]
Does the LED still blink? If so your system is booted. UART2_M0 is used as debug console (`console=ttyFIQ0,1500000n8`) by default, so if you enabled it as a normal UART, then the console will be closed as the port is now a `ttyS*`.

**Comment by nerbivol** [comment]
The LED doesn't blink at all; it just stays on. The port works as `ttyS2`, but Radxa doesn't boot when a device is connected to `UART2_M0`. I can start Radxa and then connect the device to `UART2_M0`. My question is, do I need to change anything in `/etc/kernel/cmdline`?

**Comment by RadxaYuntian** [comment]
Your UART device might malfunction with the boot log outputting on this port though.

**Comment by nerbivol** [comment]
After running `sudo apt upgrade` on my Radxa device, I can no longer connect to Wi-Fi. The device doesn't detect any available Wi-Fi networks.

**Comment by RadxaYuntian** [comment]
It is [not supported](https://docs.radxa.com/en/template/sbc/os-config/rsetup#system-update), which is why I told you to use `rsetup`.

**Comment by nerbivol** [comment]
Oh, you're right! Thank you. I'll update through `rsetup`. I was struggling with this before!
