### ISSUE TITLE
Unable to boot cli image

### ISSUE THREAD

**Issue by tester58126** [radxa-build/radxa-zero3#2]
device : radxa zero 3w

[radxa-zero3_debian_bullseye_cli_b3.img.xz]
(https://github.com/radxa-build/radxa-zero3/releases/download/b3/radxa-zero3_debian_bullseye_cli_b3.img.xz)

[radxa-zero3_ubuntu_jammy_cli_b3.img.xz]
(https://github.com/radxa-build/radxa-zero3/releases/download/b3/radxa-zero3_ubuntu_jammy_cli_b3.img.xz)

**Comment by RadxaYuntian** [comment]
CLI image is currently unbootable due to a known issue. In addition Ubuntu is not a supported system at the moment.

- Right now we only recommend and support Debian Desktop image.
