### ISSUE TITLE
IS anyone working on THIS!!!!

### ISSUE THREAD

**Issue by captclearleft** [radxa-build/radxa-zero3#22]
This hardware is useless without a working Operating System.  I cannot believe Radxa is letting this go!  Its been a year since the hardware was released without a working OS....  Any word Radxa??? Did you just throw this in bit-bucket?

**Comment by RadxaYuntian** [comment]
The latest Debian Desktop should work, which is also the only variant we officially support. Have you tried that?

**Comment by captclearleft** [comment]
That Image is unusable as it is so incredibly slow.  There is something wrong with it.  A Pi Zero running Ubuntu is faster.  There is no way that is the answer.

**Comment by RadxaYuntian** [comment]
The main reason is that the Rockchip RK356X SDK's GPU driver does not support OpenGL, so the desktop is software rendered. In addition, the SDK is currently only available in Debian 11, which ships a Mesa that does not support the specific GPU used on those chips, so we cannot use open source GPU driver that does support OpenGL.

Feel free to use 3rd party images if you don't need full hardware support.

**Comment by captclearleft** [comment]
I appreciate your responses, Thank You.  And... My point exactly - The OS provided by Radxa does not work (its a hack at best).  Further - If its the GPU OpenGL rendering the Desktop that causes the bottleneck - then the CLI version should have no problems.    I purchased several of these units, and there is still no Radxa supported OS (image)...  Radxa relying on third party images is sad, and unprofessional.  Please put a team back on this project and provide a working OS for those people that supported your product.

**Comment by RadxaYuntian** [comment]
> there is still no Radxa supported OS (image)

We do and it's the desktop image. The chip is working as intended since it never officially supports OpenGL. Rockchip merely licenses the IP from Arm, and they do not design those chips with OpenGL in mind. It's the open source driver a hack to add OpenGL (they explicitly called their implementation [non-conformant](https://docs.mesa3d.org/drivers/panfrost.html)) to otherwise unsupported hardware.
