### ISSUE TITLE
cli img not booting

### ISSUE THREAD

**Issue by wrossi** [radxa-build/radxa-zero3#5]
is there any cli image working? I tried b4,b5,b6 but they all get stuck at roofs clean

**Comment by danielfaust** [comment]
Can confirm, none of the cli images boot (also not Ubuntu). At least not on Zero 3E.

**Comment by RadxaYuntian** [comment]
Duplicate of #4

**Comment by wrossi** [comment]
yep - I only have 3W boards, and none of the cli img boot. Ubuntu img seems to blink more but no video output.
