### ISSUE TITLE
 radxa-zero3_debian_bullseye_cli_b3 stuck on boot

### ISSUE THREAD

**Issue by yungseppel** [radxa-build/radxa-zero3#6]
![975FCB89-E95F-4D5A-90E4-E035EFE746F4](https://github.com/radxa-build/radxa-zero3/assets/33831727/66b80a4c-882e-460d-954b-cd9030b59806)

My Radxa Zero 3W seems to be stuck when booting from a SD Card with the  radxa-zero3_debian_bullseye_cli_b3 image.  waited for 1,5h. It works fine with the xfce desktop version.

**Comment by RadxaYuntian** [comment]
Duplicated of #4
I'd also suggest you use [B6 image](https://github.com/radxa-build/radxa-zero3/releases/download/b6/radxa-zero3_debian_bullseye_xfce_b6.img.xz) since this version includes the support with the upgraded wireless module.

**Comment by yungseppel** [comment]
The B6 image also does not boot (stuck in the same step).

**Comment by RadxaYuntian** [comment]
Are you using the CLI version? It is known to have boot issue currently.

The link I gave is for the desktop variant.
